### ISSUE TITLE
Support all Kotlin/Native targets

### ISSUE THREAD

**Issue by natario1** [square/okio#1326] opened 2023-08-03 17:36 UTC
KMP libraries are slowly adopting the new [recommended set of targets](https://kotlinlang.org/docs/native-target-support.html#for-library-authors).
What would Okio need in order to add `androidNative` support (other than declaring the targets)?

**Comment by JakeWharton** [comment] 2024-02-15 05:02
Duplicate of #1242

**Closed by JakeWharton** 2024-02-15 05:02 UTC
