### ISSUE TITLE
byteArray.toByteString() seems broken on js platform

### ISSUE THREAD

**Issue by yschimke** [square/okio#1081] opened 2022-01-03 21:22 UTC
```
class ByteStringJsTest {
  @Test
  fun testHex() {
    assertEquals(2, byteArrayOf(1, 127).size)
    assertEquals("017f".decodeHex(), byteArrayOf(1, 127).toByteString())
  }

  @Test
  fun testHexDefaults() {
    assertEquals("017f".decodeHex(), byteArrayOf(1, 127).toByteString(0, 2))
  }
}
```

```
AssertionError: Expected <[hex=017f]>, actual <[size=0]>.
```

Maybe something wrong with my platform, but can't see what.  I can't see any tests of this in commonTest or jsTest though.

**Comment by yschimke** [comment] 2022-01-08 14:41
Seems to fail here

```
    /**
     * Returns a new [ByteString] containing a copy of `byteCount` bytes of this [ByteArray]
     * starting at `offset`.
     */
    @JvmStatic
    fun ByteArray.toByteString(offset: Int = 0, byteCount: Int = this.size.also {
      println("Before")
      println(this)
      println(this.size)
      println("After")
    }): ByteString
```

Before
[object Object]
undefined
After

**Comment by yschimke** [comment] 2022-01-08 16:07
Reported as https://youtrack.jetbrains.com/issue/KT-50681

**Comment by swankjesse** [comment] 2022-01-08 18:15
I think this is a duplicate of https://youtrack.jetbrains.com/issue/KT-45542

**Comment by yschimke** [comment] 2022-01-08 18:36
Thanks! is it valid to keep this open to track, are other users appropriately worked around?

**Comment by yschimke** [comment] 2022-01-08 18:37
What would a good sentinel value be? MIN_INT? -1?

**Comment by swankjesse** [comment] 2022-01-08 20:23
` -1234567890`.

https://github.com/square/okio/blob/3e3b82b2ab104dc5b16ff509897b0575559833a0/okio/src/commonMain/kotlin/okio/-Util.kt#L163

**Closed** 2022-01-10 18:32 UTC
