### ISSUE TITLE
Strange NullPointerException at InputStreamSource caused by OkHttp when network no response.

### ISSUE THREAD

**Issue by 1001101** [square/okio#561] opened 2019-03-06 04:48 UTC
The variable must not `null` at line 104, but it happens. Maybe caused by Android runtime?

![screenshot from 2019-03-06 12-36-48](https://user-images.githubusercontent.com/12015910/53856642-bd86ee80-400d-11e9-9eab-4642c75ca8db.png)

```
 Throwing new exception 'Attempt to read from field 'okio.AsyncTimeout okio.AsyncTimeout$source$1.this$0' on a null object reference' with unexpected pending exception: java.lang.NullPointerException: Attempt to read from field 'int okio.Segment.limit' on a null object reference
   at long okio.InputStreamSource.read(okio.Buffer, long) (Okio.kt:104)
   at long okio.AsyncTimeout$source$1.read(okio.Buffer, long) (AsyncTimeout.kt:159)
   at long okio.RealBufferedSource.indexOf(byte, long, long) (RealBufferedSource.kt:349)
   at java.lang.String okio.RealBufferedSource.readUtf8LineStrict(long) (RealBufferedSource.kt:222)
   at java.lang.String okhttp3.internal.http1.Http1Codec.readHeaderLine() (Http1Codec.java:215)
   at okhttp3.Response$Builder okhttp3.internal.http1.Http1Codec.readResponseHeaders(boolean) (Http1Codec.java:189)
   at okhttp3.Response okhttp3.internal.http.CallServerInterceptor.intercept(okhttp3.Interceptor$Chain) (CallServerInterceptor.java:88)
   at okhttp3.Response okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection) (RealInterceptorChain.java:147)
   at okhttp3.Response okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request) (RealInterceptorChain.java:121)

```

**Comment by swankjesse** [comment] 2019-03-07 12:25
Occasionally crashes in Okio are due to concurrency bugs. If you're accessing a stream or buffer from multiple threads it could be incorrectly accessing the wrong segments.

**Comment by 1001101** [comment] 2019-03-12 12:14
the local variable `tail` at line 104 must not be null because NPE didn't throws at line 102.

**Comment by swankjesse** [comment] 2019-04-28 22:02
Duplicate of https://github.com/square/okio/issues/163

**Closed by swankjesse** 2019-04-28 22:02 UTC
