### ISSUE TITLE
deadlineNanoTime: IllegalStateException: No deadline

### ISSUE THREAD

**Issue by yogurtearl** [square/okio#160] opened 2015-07-14 21:35 UTC
Got this crash once on crashlytics from an Nexus 6 running 5.1.1. 
We are using retrofit 1.9.0 and okhttp 2.3.0 ( with very small ~~seemly unrelated~~ modifications ).

In our OkHttp, we always call isReadable before reusing a connection.

Mainly filing it for people to google and add related info. 

```
retrofit.RetrofitError: No deadline
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
       at retrofit.RxSupport$2.run(RxSupport.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at ██████████████████Executor$1.run(███████████Executor.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: No deadline
       at okio.Timeout.deadlineNanoTime(Timeout.java:104)
       at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:84)
       at okio.AsyncTimeout.enter(AsyncTimeout.java:69)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
       at com.squareup.okhttp.internal.http.HttpConnection.isReadable(HttpConnection.java:153)
       at com.squareup.okhttp.Connection.isReadable(Connection.java:306)
       at com.squareup.okhttp.OkHttpClient$1.isReadable(OkHttpClient.java:87)
       at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:339)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.execute(Call.java:79)
       at retrofit.client.OkClient.execute(OkClient.java:53)
       at ██████████████████OkClient.execute(████████OkClient.java:46)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
       at retrofit.RxSupport$2.run(RxSupport.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at ██████████████Executor$1.run(██████████████Executor.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by JakeWharton** [comment] 2015-07-14 21:48
Dupe of #133. Fixed by https://github.com/square/okhttp/pull/1654. Are you using 2.4.0?

**Comment by JakeWharton** [comment] 2015-07-14 21:48
No you are not. RTFM, Jake. A quick upgrade to 2.4 should fix!

**Closed by JakeWharton** 2015-07-14 21:48 UTC

**Comment by swankjesse** [comment] 2015-07-15 02:02
I love the redacted stacktraces. You're a ███ing genius!
