### ISSUE TITLE
Segment pool should be thread local

### ISSUE THREAD

**Issue by yyfrankyy** [square/okio#163] opened 2015-07-30 16:18 UTC
okio version: 1.4.0
okhttp version: 2.4.0

``` Java
java.lang.NullPointerException: Attempt to write to field 'okio.Segment okio.Segment.prev' on a null object reference
    at okio.Segment.push(Segment.java:96)
    at okio.Buffer.writableSegment(Buffer.java:1120)
    at okio.Buffer.write(Buffer.java:940)
    at okio.Buffer$1.write(Buffer.java:74)
    at java.io.OutputStream.write(OutputStream.java:82)
    at retrofit.mime.JSONEncodedTypedOutput.writeTo(JSONEncodedTypedOutput.java:56)
    at retrofit.client.OkClient$1.writeTo(OkClient.java:88)
```

``` Java
java.lang.ArrayIndexOutOfBoundsException: length=2048; index=2048
    at okio.Buffer.writeUtf8(Buffer.java:818)
    at com.squareup.okhttp.HttpUrl.percentDecode(HttpUrl.java:1366)
    at com.squareup.okhttp.HttpUrl.percentDecode(HttpUrl.java:1349)
    at com.squareup.okhttp.HttpUrl.percentDecode(HttpUrl.java:1355)
    at com.squareup.okhttp.HttpUrl.<init>(HttpUrl.java:308)
    at com.squareup.okhttp.HttpUrl.<init>(HttpUrl.java:255)
    at com.squareup.okhttp.HttpUrl$Builder.build(HttpUrl.java:833)
    at com.squareup.okhttp.HttpUrl$Builder.parse(HttpUrl.java:999)
    at com.squareup.okhttp.HttpUrl.parse(HttpUrl.java:585)
    at com.squareup.okhttp.Request$Builder.url(Request.java:156)
    at retrofit.client.OkClient.createRequest(OkClient.java:57)
    at retrofit.client.OkClient.execute(OkClient.java:53)
```

And sometimes the `ArrayIndexOutOfBoundsException` happens in `writeInt`, or reading the Response stream returned corrupted data.

These two exceptions happens a lot while in multi thread, I reviewed all the source code still do not know why..

**Comment by swankjesse** [comment] 2015-07-30 16:27
Are you accessing the same stream from multiple threads?

**Comment by yyfrankyy** [comment] 2015-07-30 16:54
Yes, I reviewed our code and found that we passed the okhttp's `Response` to another thread, so that will be an issue to corrupt the whole pool? I've seen some cases just `new Buffer()` and write/read in just one method.

**Comment by swankjesse** [comment] 2015-07-31 07:17
Typically this kind of problem suggests you're accessing a stream from multiple threads concurrently.

If you can isolate the problem into a test case, that'd be helpful.

**Comment by yyfrankyy** [comment] 2015-08-02 17:51
Hi, I found a way to reproduce this, when `buffer` is reading/writing concurrently and exception is swallowed, the follow `shareAndSplit()` test might fail.

```
@Test public void useBufferInMultipleThread() throws Exception {
  final Buffer buffer = new Buffer();
  for (int i = 0; i < 100; i++) {
    new Thread(new Runnable() {
      @Override
      public void run() {
        try {
          buffer.writeInt(1).readInt();
        } catch (Throwable ignored) { }

        try {
          shareAndSplit();
        } catch (Exception e) {
          fail(e.getMessage());
        }
      }
    }).start();
  }
```

**Comment by swankjesse** [comment] 2015-08-02 18:42
That's expected; Buffer is not thread safe.

**Comment by yyfrankyy** [comment] 2015-08-03 02:41
I understood that one Buffer object is not thread safe, but `SegmentPool` claimed to be thread safe. If there is a misuse on one buffer, others might be affected. I think it's necessary to make sure recycling a segment into pool is thread safe too.

**Comment by swankjesse** [comment] 2015-08-03 03:16
Yeah, I get where you're coming from. A bug in one part of your application shouldn't impact another unrelated part of your application.

**Comment by swankjesse** [comment] 2015-08-03 03:17
I think we fix this by making segment sharing thread local.

**Comment by swankjesse** [comment] 2015-08-03 03:17
(that also fixes other problems, such as lock contention on the pool.)

**Comment by yyfrankyy** [comment] 2015-08-03 14:36
https://github.com/yyfrankyy/okio/commit/bab3a2b1d44e572af755f2d9bdaf5faeb7c6cd5b

I did a little dirty fix, remove the `synchronized` lock do get a little more throughput.

Benchmark result: https://gist.github.com/yyfrankyy/1027c0c979fca027fe9d

**Comment by akshayanv** [comment] 2018-01-24 19:08
Did the fix for this land in any version of okio so far?

**Comment by swankjesse** [comment] 2018-01-25 03:04
No.

**Comment by youlingwangzi** [comment] 2018-03-31 07:59
we're hitting it from a WEBVIEW html app when playing video too.
`
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
	at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
        .......
	at android.media.MediaHTTPConnection.getMIMEType(MediaHTTPConnection)
`
How can we fix it?

**Comment by akshayanv** [comment] 2018-03-31 08:16
It seems like the cause is multi-threading in the client process which may be talking to the server process running MediaHTTPConnection in a binder transaction setup. Using mutual exclusion in the client process code may fix the race conditions on okio buffer.



-----Original Message-----

**Comment by slott** [comment] 2018-08-27 07:47
Not sure if this is the same thing, but I've just got something very similar from our latest production build...

```
Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'com.android.vivino.jsonModels.TasteCharacteristicsResponse com.android.vivino.winedetails.bw.b' on a null object reference
       at com.android.vivino.winedetails.VintageDetailsActivity$9.com.android.vivino.winedetails.VintageDetailsAdapter.setTasteCharacteristics(VintageDetailsActivity.java:2870)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

None of our QA staff have been able to reproduce the crash so its rare - but with 20mill+ users it happens.

I'm using the latest retrofit 2.4 - was there any solution to this ?

**Comment by swankjesse** [comment] 2018-08-27 11:35
I don't think this is related.

**Comment by 15characterlimi** [comment] 2019-03-08 16:08
Re this bug's title "Segment pool should be thread local", wouldn't a ThreadLocal mean that you'd effectively leak memory because all kinds of long running threads might indefinitely hold on to a 64 KByte buffer of Segments?

Alternatives that I can think of are:

 (1) stop buffering altogether, always allocate a new Segment. This is easy and safe, but I don't know the performance impact.
 (2) Use SegmentPool instances, have clients decide how widely they'd like to share SegmentPool instances. Clients are then free to decide whether to use 
  (a) a statically referenced global singleton,
  (b) a  statically referenced SegmentPool implementation/instance with maximum size 0, ie. one that always allocates new Segments,
  (c) share a SegmentPool instance throughout some portion of their application.

For example, OkHttpClient.Builder would do (c) and use a (potentially different) SegmentPool instance per OkHttpClient instance, which means that one OkHttpClient instance that is configured to have its own SegmentPool instance can not be messed up by buggy other OkHttpClient instances.

The downside of course is that the SegmentPool instance configured in the OkHttpClient needs to be passed down all the way to okio.Buffer. (Ie., the SegmentPool instance would need to be injected into the okio.Buffer ctor or similar, rather than Buffer having a no-arg ctor like it has now).

**Comment by swankjesse** [comment] 2019-03-09 00:19
Yep, hence we've been sitting on this one for a while.

**Comment by swankjesse** [comment] 2019-04-13 13:36
Example: https://issuetracker.google.com/issues/130410728

**Comment by bendb-instacart** [comment] 2019-08-07 21:36
Is it fair to say that this is implemented?  I see that in 2.3.0 we have 

```
@ThreadLocal
internal object SegmentPool {
  ...
}
```

**Comment by 15characterlimi** [comment] 2019-08-07 21:48
@bendb-instacart that suggests that a quick/hacky fix has been implemented, but note that that approach has downsides (specifically that each thread that makes a network connection holds on to 64 KBytes of memory for as long as the thread exists, see my comment above), which is probably while this issue here has not yet been marked as resolved.

**Comment by swankjesse** [comment] 2019-08-08 01:47
That's for Kotlin native only.

**Comment by swankjesse** [comment] 2024-02-04 19:52
We did almost exactly this.
okio/src/jvmMain/kotlin/okio/SegmentPool.kt

**Closed by swankjesse** 2024-02-04 19:52 UTC
Labels: bug
