### ISSUE TITLE
"Explicit termination method 'end' not called" in GzipSource.<init>

### ISSUE THREAD

**Issue by microstudent** [square/okio#359] opened 2018-03-05 09:07 UTC
Hi, there is a log reporting that GzipSource doesnt call inflater.end() when StrictMode is enabled.

> java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.util.zip.Inflater.<init>(Inflater.java:104)
at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:823)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
...omit some lines
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

Should it be repaired?

**Comment by swankjesse** [comment] 2018-03-05 11:55
Are you closing your response body when you're done with it?

**Comment by JakeWharton** [comment] 2018-03-05 13:28
This is the version of OkHttp and Okio embeded in Android. I'm pretty sure this has already been fixed.

**Comment by microstudent** [comment] 2018-03-07 10:05
ok, so I found a comment on 
[https://github.com/square/okhttp/blob/c9b812a4ab75bfbf1e1de439ee719fa700a592f1/okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java#L129]()

>  // This doesn't close the stream because doing so would require all stream
    // access to be synchronized. It's expected that the thread using the
    // connection will close its streams directly. If it doesn't, the worst
    // case is that the GzipSource's Inflater won't be released until it's
    // finalized. (This logs a warning on Android.)

I do call HttpURLConnection.disconnect() after I am done with it.
So what I should do is to make sure that all the streams opend by the connection are closed properly, right?

**Closed** 2018-03-07 12:57 UTC

**Comment by harshit-inmobi** [comment] 2021-06-07 14:06
Any update on this, I'm facing similar issue.

`2021-06-03 18:13:48.077 8431-10090/com.bambuna.podcastaddict D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)
at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)
at java.util.zip.Inflater.finalize(Inflater.java:407)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
at java.lang.Daemons$Daemon.run(Daemons.java:139)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)
at dalvik.system.CloseGuard.open(CloseGuard.java:230)
at java.util.zip.Inflater.<init>(Inflater.java:122)
at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:64)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:619)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:811)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)`

**Comment by harshit-inmobi** [comment] 2021-06-08 11:17
> ok, so I found a comment on [here](https://github.com/square/okhttp/blob/c9b812a4ab75bfbf1e1de439ee719fa700a592f1/okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java#L129)
> 
> > // This doesn't close the stream because doing so would require all stream
> > // access to be synchronized. It's expected that the thread using the
> > // connection will close its streams directly. If it doesn't, the worst
> > // case is that the GzipSource's Inflater won't be released until it's
> > // finalized. (This logs a warning on Android.)
> 
> I do call HttpURLConnection.disconnect() after I am done with it.
> So what I should do is to make sure that all the streams opend by the connection are closed properly, right?

I'm facing the same issue, did you get any resolution for this? @microstudent 

> 2021-06-03 18:13:48.077 8431-10090/com.bambuna.podcastaddict D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)
at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)
at java.util.zip.Inflater.finalize(Inflater.java:407)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
at java.lang.Daemons$Daemon.run(Daemons.java:139)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)
at dalvik.system.CloseGuard.open(CloseGuard.java:230)
at java.util.zip.Inflater.(Inflater.java:122)
at com.android.okhttp.okio.GzipSource.(GzipSource.java:64)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:619)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:811)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
