### ISSUE TITLE
dead loop hanpens in okio AsyncTimeout (okio1.6.0)

### ISSUE THREAD

**Issue by sunsee** [square/okio#214] opened 2016-04-21 02:08 UTC
at okio.AsyncTimeout.cancelScheduledTimeout(AsyncTimeout.java:117)	
  at okio.AsyncTimeout.exit(AsyncTimeout.java:111)	
  at okio.AsyncTimeout.exit(AsyncTimeout.java:249)	
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)	
  at okio.RealBufferedSource.read(RealBufferedSource.java:50)	
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)	
  at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)	
  at java.io.InputStream.read(InputStream.java:162)	
.....

My android app has ANR ,and here is the call stack which block the program,
It seems that  fucntion cancelScheduledTimeout has some deadloop.

Is this issue solved in 1.7.0 ?

==sorry ，  the  call stack is  wrong.
Here is the right call stack:
  at okio.AsyncTimeout.cancelScheduledTimeout(AsyncTimeout.java:117) 
  at okio.AsyncTimeout.exit(AsyncTimeout.java:111) 
  at okio.AsyncTimeout.exit(AsyncTimeout.java:249) 
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:217) 
  at okio.RealBufferedSource.read(RealBufferedSource.java:50) 
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381) 
  at okhttp3.internal.Util.skipAll(Util.java:178) 
  at okhttp3.internal.Util.discard(Util.java:160) 
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:397) 
  at okio.RealBufferedSource.close(RealBufferedSource.java:396) 
  at okio.RealBufferedSource$1.close(RealBufferedSource.java:384) 
...

**Comment by sunsee** [comment] 2016-04-21 02:14
And there is another thread also has dead loop, here is the call stack:
  at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:96)	
  at okio.AsyncTimeout.enter(AsyncTimeout.java:69)	
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)	
  at okio.RealBufferedSource.read(RealBufferedSource.java:50)	
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)	
  at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)	
  at java.io.InputStream.read(InputStream.java:162)	
  at com.tencent.wecarCodecEngine.Http.DownloadEntity.write2File(DownloadEntity.java:243)	
  at com.tencent.wecarCodecEngine.Http.DownloadEntity.beginDownload(DownloadEntity.java:144)	
  at com.tencent.wecarCodecEngine.Http.DownloadEntity.beginDownload(DownloadEntity.java:127)	
  at com.tencent.wecarCodecEngine.Http.DownLoadThread.downloadRun(DownLoadThread.java:85)	
  at com.tencent.wecarCodecEngine.Http.DownLoadThread.access$0(DownLoadThread.java:61)	
  at com.tencent.wecarCodecEngine.Http.DownLoadThread$1.run(DownLoadThread.java:26)

**Comment by sunsee** [comment] 2016-04-21 02:17
It seems the  single-linked list of AsyncTimeout has internal loop..

**Comment by swankjesse** [comment] 2016-04-21 17:09
Just curious: are you using ProGuard?

**Comment by swankjesse** [comment] 2016-04-21 17:10
If you are, it could be related to https://github.com/square/okio/issues/185

**Comment by swankjesse** [comment] 2016-04-24 14:12
@sunsee I’d really like your help reproducing this. At the moment I can’t see how that internal loop could be created.

**Comment by sunsee** [comment] 2016-04-25 03:33
There are 2 thread：
1 thread called inputstream.read and the call stack:
at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:96)

at okio.AsyncTimeout.enter(AsyncTimeout.java:69)

at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)

at okio.RealBufferedSource.read(RealBufferedSource.java:50)

at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)

at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)

at java.io.InputStream.read(InputStream.java:162) 
.....


another thread called inputstream.close , and the call stack:

  at okio.AsyncTimeout.cancelScheduledTimeout(AsyncTimeout.java:117) 
  at okio.AsyncTimeout.exit(AsyncTimeout.java:111) 
  at okio.AsyncTimeout.exit(AsyncTimeout.java:249) 
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:217) 
  at okio.RealBufferedSource.read(RealBufferedSource.java:50) 
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381) 
  at okhttp3.internal.Util.skipAll(Util.java:178) 
  at okhttp3.internal.Util.discard(Util.java:160) 
  at okhttp3.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:397) 
  at okio.RealBufferedSource.close(RealBufferedSource.java:396) 
  at okio.RealBufferedSource$1.close(RealBufferedSource.java:384) 
......

This issue happens seldom. 
It seems that  function scheduleTimeout has the dead loop in this section:(because  the call stack is sometimes add remainingNanos())

    for (AsyncTimeout prev = head; ; prev = prev.next)
      if ((prev.next == null) || (remainingNanos < prev.next.remainingNanos(now))) {
        node.next = prev.next;
        prev.next = node;
        if (prev != head) break;
        AsyncTimeout.class.notify(); break;
      }

And the other thread is stucked becasue  function cancelScheduledTimeout() need synchronized the same class.

**Comment by swankjesse** [comment] 2016-05-02 04:07
Duplicate of https://github.com/square/okio/issues/185

**Closed by swankjesse** 2016-05-02 04:07 UTC
