### ISSUE TITLE
static singleton SegmentPool doesn't isolate correct code from buggy code's behavior

### ISSUE THREAD

**Issue by 15characterlimi** [square/okio#560] opened 2019-03-04 15:37 UTC
I'm filing this issue for discussion, please feel free to close as WAI.

Buggy use of SegmentPool by client X can mess up client Y, as long as they run in the same process. This is an undesirable side effect of the fact that SegmentPool currently maintains a *static* cache, shared between everyone who runs in the same process. It's undesirable because when the program is sufficiently large/complex, the two parts of the application might not and should not need to know about each other. The lack of isolation/encapsulation between the two components leads to incorrectly assigned blame and hard to investigate bugs.

Specifically, if some client continues to modify a Segment after they've recycle()d it, they'll mess up another client that has since take()n the same Segment out of the pool. 

For example, a thread unsafe use of HttpURLConnectionImpl could lead to thread A having called recycle(Segment) but thread B continuing to use that Segment; thread C which is using a separate instance of HttpURLConnectionImpl who take()s that Segment could then encounter unspecified behavior even though C's interaction with HttpURLConnection is correct. I've seen a crash similar to https://github.com/square/okhttp/issues/3662 that I believe was caused by this.

Possible solutions:

(a) This could be avoided if the pool of Segments was specific to the *instance* of SegmentPool used rather than a static singleton pool. Clients that want the static singleton semantics could still call a static / @JvmStatic method getDefault() to obtain the global shared instance, but clients would also have a choice of constructing a new SegmentPool instance of choosing themselves how broadly they would like to share it. For example, all HttpURLConnection instances used by a particular library could share the same SegmentPool instance but not share it with HttpURLConnection instances elsewhere in the same process. For example, OkHttpClient.Builder.segmentPool(SegmentPool) might set a SegmentPool instance to be shared between the OkHttpClient instances constructed by that Builder. If unset, it could default to the static global default SegmentPool instance; or the default could be the other way around, consistent with Builder.connectionPool().

(b) Obviously, the problem would also go away if one disabled caching altogether by setting MAX_SIZE to 0, because then Segments would never be reused. But I'm guessing that you have benchmarks to prove that the existence of SegmentPool makes a significant performance difference. Right?

What do you think?

**Comment by 15characterlimi** [comment] 2019-03-04 16:31
PS. If we went to multiple separate SegmentPool instances, then they could have separate MAX_SIZE (and perhaps even Segment size?) values. There could be a use case for a static SegmentPool noCache() factory/instance whose MAX_SIZE is 0.

**Comment by swankjesse** [comment] 2019-03-07 12:28
Yeah, let's fix. Discussion had already started and stalled here.

https://github.com/square/okio/issues/163

I'll close this as a duplicate of that.

**Closed by swankjesse** 2019-03-07 12:28 UTC
