### ISSUE TITLE
Llink to proguard file is broken

### ISSUE THREAD

**Issue by MarcelReiter** [square/okio#1320] opened 2023-07-31 07:25 UTC
On your website: https://square.github.io/okio/ 
there is a section called `r8 / proguard`: https://square.github.io/okio/#r8-proguard
linking to a missing file: https://github.com/square/okio/blob/master/okio/src/jvmMain/resources/META-INF/proguard/okio.pro

**Comment by oldergod** [comment] 2023-07-31 12:06
Duplicate of https://github.com/square/okio/issues/1302

Do we need to publish the website @swankjesse ? I thought this was automatic. Maybe for releases only?

**Comment by swankjesse** [comment] 2023-07-31 12:17
Yeah we need to trigger that action, and currently that only happens with a release.

**Comment by swankjesse** [comment] 2023-08-02 21:15
Fixed.

**Closed by swankjesse** 2023-08-02 21:15 UTC
